apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lidarr-cert
spec:
  secretName: lidarr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - lidarr.kevingomez.fr
