apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`lidarr.kevingomez.fr`)
      middlewares:
        - name: forwardauth-authelia
          namespace: authelia
      services:
        - kind: Service
          name: lidarr
          port: http
  tls:
    secretName: lidarr-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr-http
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`lidarr.kevingomez.fr`)
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - kind: Service
          name: lidarr
          port: http