apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: nanoflux
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rss.kevingomez.fr`)
      middlewares:
        - name: forwardauth-authelia
          namespace: authelia
      services:
        - kind: Service
          name: nanoflux
          port: http
  tls:
    secretName: nanoflux-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nanoflux-http
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`rss.kevingomez.fr`)
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - kind: Service
          name: nanoflux
          port: http