apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-password
spec:
  itemPath: "vaults/Homelab/items/nanoflux - postgres"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nanoflux-db-url
spec:
  itemPath: "vaults/Homelab/items/nanoflux - DB url"
