apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.2.6
  - overlays/argo-ingress.yaml

patches:
  - path: overlays/argo-cd-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
  - path: overlays/argocd-cmd-params-cm.yaml
