homelab:
  hosts:
    potato:
      ansible_host: 10.10.10.122
      #ansible_host: 100.116.86.9
      ansible_port: 4242

      alloy_node_exporter_enabled: true

    carrot:
      ansible_host: 10.10.10.64
      #ansible_host: 100.111.87.49
      ansible_port: 4242

      k3s_master: true
      blocky_enabled: true
      keepalived_exporter__arch: amd64
      keepalived__vrrp_priority__blocky: 100
      keepalived__vrrp_priority__k3s: 150 # higher is better

    bean:
      ansible_host: 10.10.10.91
      #ansible_host: 100.87.198.114
      ansible_port: 4242

      k3s_master: true
      blocky_enabled: true
      keepalived_exporter__arch: amd64
      keepalived__vrrp_priority__blocky: 150 # higher is better
      keepalived__vrrp_priority__k3s: 100

    celery:
      ansible_host: 10.10.10.14
      #ansible_host: 100.71.153.60
      ansible_port: 4242

      k3s_master: true
      blocky_enabled: true
      keepalived_exporter__arch: amd64
      keepalived__vrrp_priority__blocky: 80
      keepalived__vrrp_priority__k3s: 80
